### ISSUE TITLE
fails to build with aeson-2.2

### ISSUE THREAD

**Issue by juhp** [eskimor/servant-subscriber#25]
For Stackage Nightly
```
       /home/curators/work/unpack-dir/unpacked/servant-subscriber-0.7.0.0-8f0a4cf5c7c340c347c6b9117c809c9dbf7c15a4c94d80d1f07bd2e3f4
7308c9/src/Servant/Subscriber/Response.hs:9:1: error: [GHC-87110]
           Could not load module ‘Data.Aeson.Parser’.                                                                               
           It is a member of the hidden package ‘attoparsec-aeson-2.2.0.1’.                                                         
           Perhaps you need to add ‘attoparsec-aeson’ to the build-depends in your .cabal file.
           Use -v to see a list of the files searched for.                                                                          
         |                                                                                                                          
       9 | import           Data.Aeson.Parser              (value)                                                                  
         | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
