### ISSUE TITLE
compile with servant 0.16.2

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-subscriber#23]
Trying to `stack build` servant-purescript with stackage lts-14, I get:

```
servant-subscriber  > /tmp/stack32501/servant-subscriber-0.6.0.2/src/Servant/Subscriber/Subscribable.hs:80:10: warning: [-Wmissing-methods]
servant-subscriber  >     • No explicit implementation for
servant-subscriber  >         ‘hoistServerWithContext’
servant-subscriber  >     • In the instance declaration for
servant-subscriber  >         ‘HasServer (Subscribable :> sublayout) context’
servant-subscriber  >    |          
servant-subscriber  > 80 | instance HasServer sublayout context => HasServer (Subscribable :> sublayout) context where
servant-subscriber  >    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
servant-subscriber  > [2 of 8] Compiling Servant.Subscriber.Types
servant-subscriber  > [3 of 8] Compiling Servant.Subscriber.Request
servant-subscriber  > [4 of 8] Compiling Servant.Subscriber.Response
servant-subscriber  >               
servant-subscriber  > /tmp/stack32501/servant-subscriber-0.6.0.2/src/Servant/Subscriber/Response.hs:81:21: error:
servant-subscriber  >     Not in scope: type constructor or class ‘ServantErr’
servant-subscriber  >    |          
servant-subscriber  > 81 | fromServantError :: ServantErr -> HttpResponse

**Comment by legrostdg** [comment]
Oh, I forgot I already submitted a pull request for this, that you merged... Could you issue a new release?

**Comment by eskimor** [comment]
sure - I can do that.

**Comment by eskimor** [comment]
Should be fixed now, thanks!

**Comment by legrostdg** [comment]
I don't see the new release :( Maybe you forgot to push something?

**Comment by eskimor** [comment]
Yeah - I forgot to push the tag, the hackage release is there though. (And now the tag as well.) - Thanks for the catch!
