### ISSUE TITLE
Compatibility with servant 0.10 / 0.11

### ISSUE THREAD

**Issue by felixSchl** [eskimor/servant-subscriber#13]
I am currently getting this when compiling with servant 0.10

```
    [1 of 8] Compiling Servant.Subscriber.Subscribable ( src/Servant/Subscriber/Subscribable.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/Servant/Subscriber/Subscribable.o )

    /private/var/folders/px/n0ytrp6d72l5m7rm8d7rgsvc0000gn/T/stack43633/servant-subscriber-0.5.0.3/src/Servant/Subscriber/Subscribable.hs:98:5: error:
        Ambiguous occurrence ‘And’
        It could refer to either ‘Servant.And’,
                                 imported from ‘Servant’ at src/Servant/Subscriber/Subscribable.hs:28:1-24
                                 (and originally defined in ‘Servant.API.TypeLevel’)
                              or ‘Servant.Subscriber.Subscribable.And’,
                                 defined at src/Servant/Subscriber/Subscribable.hs:97:1

    /private/var/folders/px/n0ytrp6d72l5m7rm8d7rgsvc0000gn/T/stack43633/servant-subscriber-0.5.0.3/src/Servant/Subscriber/Subscribable.hs:101:5: error:
        Ambiguous occurrence ‘Elem’
        It could refer to either ‘Servant.Elem’,
                                 imported from ‘Servant’ at src/Servant/Subscriber/Subscribable.hs:28:1-24
                                 (and originally defined in ‘Servant.API.TypeLevel’)
                              or ‘Servant.Subscriber.Subscribable.Elem’,
                                 defined at src/Servant/Subscriber/Subscribable.hs:100:1

    /private/var/folders/px/n0ytrp6d72l5m7rm8d7rgsvc0000gn/T/stack43633/servant-subscriber-0.5.0.3/src/Servant/Subscriber/Subscribable.hs:102:5: error:
        Ambiguous occurrence ‘Elem’
        It could refer to either ‘Servant.Elem’,
                                 imported from ‘Servant’ at src/Servant/Subscriber/Subscribable.hs:28:1-24
                                 (and originally defined in ‘Servant.API.TypeLevel’)
                              or ‘Servant.Subscriber.Subscribable.Elem’,
                                 defined at src/Servant/Subscriber/Subscribable.hs:100:1

    /private/var/folders/px/n0ytrp6d72l5m7rm8d7rgsvc0000gn/T/stack43633/servant-subscriber-0.5.0.3/src/Servant/Subscriber/Subscribable.hs:102:24: error:
        Ambiguous occurrence ‘Elem’
        It could refer to either ‘Servant.Elem’,
                                 imported from ‘Servant’ at src/Servant/Subscriber/Subscribable.hs:28:1-24
                                 (and originally defined in ‘Servant.API.TypeLevel’)
                              or ‘Servant.Subscriber.Subscribable.Elem’,
                                 defined at src/Servant/Subscriber/Subscribable.hs:100:1
```

**Comment by felixSchl** [comment]
I understand that the new versions of servant are not available in a lts yet (0.10 is available in a nightly). Do we just wait it out or can we prepare for this already? I see that the various stack yamls target a specific lts, so take make these updates should I add another yaml temporarily? I'll see if I can fix it in a way it works on both versions (0.9 and 0.10)

**Comment by felixSchl** [comment]
Sorry just found #11 :)
