### PR TITLE
Build with servant 0.14 

### LINKED ISSUE #17: servant-subscriber 0.6.0.1 build failure with servant 0.14
As seen on the Stackage build server:

```
[1 of 8] Compiling Servant.Subscriber.Subscribable ( src/Servant/Subscriber/Subscribable.hs, dist/build/Servant/Subscriber/Subscribable.o )

src/Servant/Subscriber/Subscribable.hs:91:10: error:
    • Number of parameters must match family declaration; expected 2
    • In the type instance declaration for ‘MkLink’
      In the instance declaration for ‘HasLink (Subscribable :> sub)’
   |
91 |     type MkLink (Subscribable :> sub) = MkLink sub
   |          ^^^^^^
```

I was able to reproduce this locally like so:

```bash
stack unpack servant-subscriber-0.6.0.1 && cd servant-subscriber-0.6.0.1
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks
```

```yaml
# stack.yaml
resolver: nightly-2018-07-04
extra-deps:
- servant-0.14
- servant-server-0.14
```

### PR DESCRIPTION
**Pull request by smobs**
Add the missing target type to HasLink.

Fixes #17 

I've tested that it builds some purescript that compiles, but not in a real scenario.

If I'm honest I'm not entirely sure I should be using the Link type directly.

I thought I'd open a PR in case this is useful to someone.

### CODE REVIEW

**Comment by shmish111** [comment]
Is this going to be merged? The same needs to be done for servant-purescript.

**Comment by eskimor** [comment]
@shmish111 does that PR looks good to you? It does look reasonable to me, but I am not up2data on recent servant developments so I don't really know.

**Comment by shmish111** [comment]
It looks good to me, in fact I am using it and it seems to build fine. The only issue is that Travis is failing here due to it trying to build multiple versions. I don't really know anything about this Travis setup though so I don't know how you would fix that.

**Comment by shmish111** [comment]
sweet, thanks @eskimor . Do you know who would be responsible for doing the same for servant-purescript?

**Comment by eskimor** [comment]
Well both are open source projects. Anyone can do it and I will happily merge any changes that look good to me, ideally I get some community responses that those changes are right and needed as I myself don't use those projects right now.

**Comment by shmish111** [comment]
ok, I'll create a PR when I get chance, maybe this week.
