### ISSUE TITLE
fails to build with stackage nightly: ServantErr & hoistServerWithContext

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-subscriber#21]
I tried to add `servant-subscriber` & `servant-purescript` back to stackage (see https://github.com/commercialhaskell/stackage/pull/4546). They seem to build fine with lts-13.20, but fail with nightly:

```
[1 of 8] Compiling Servant.Subscriber.Subscribable ( src/Servant/Subscriber/Subscribable.hs, dist/build/Servant/Subscriber/Subscribable.o )

src/Servant/Subscriber/Subscribable.hs:80:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘hoistServerWithContext’
    • In the instance declaration for
        ‘HasServer (Subscribable :> sublayout) context’
   |
80 | instance HasServer sublayout context => HasServer (Subscribable :> sublayout) context where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2 of 8] Compiling Servant.Subscriber.Types ( src/Servant/Subscriber/Types.hs, dist/build/Servant/Subscriber/Types.o )
[3 of 8] Compiling Servant.Subscriber.Request ( src/Servant/Subscriber/Request.hs, dist/build/Servant/Subscriber/Request.o )
[4 of 8] Compiling Servant.Subscriber.Response ( src/Servant/Subscriber/Response.hs, dist/build/Servant/Subscriber/Response.o )

src/Servant/Subscriber/Response.hs:81:21: error:
    Not in scope: type constructor or class ‘ServantErr’
   |
81 | fromServantError :: ServantErr -> HttpResponse
   |                     ^^^^^^^^^^
```

**Comment by eskimor** [comment]
Thanks for reporting!

**Comment by legrostdg** [comment]
Do you think you'll be able to fix these? I can have a look, but it's always harder for a non-maintainer to try to fix someone else's code...

**Comment by legrostdg** [comment]
the second one is easy, and I did not see the first one was only a warning...

**Comment by legrostdg** [comment]
@eskimor Could you push a new release?

**Comment by eskimor** [comment]
I would, but I would like to have that warnings checked out first. If you have some time, it would be cool if you had a look at them. They could be severe, I am not really comfortable making a release without having more knowledge about them.

**Comment by legrostdg** [comment]
Sorry, this `hoistServerWithContext` does not make much sense to me...

**Comment by eskimor** [comment]
Ok, I'll have a look when I find some time.
